# Generated by Django 3.2.7 on 2021-09-24 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('address_line_2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('phone_1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('phone_2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
