# Generated by Django 3.2.7 on 2021-09-26 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210926_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_leaves', models.IntegerField(blank=True, default=24, null=True)),
                ('approved_leaves', models.IntegerField(blank=True, default=0, null=True)),
                ('pending_leaves', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('EMPLOYEE', 'EMPLOYEE'), ('MANAGER', 'MANAGER'), ('HR_MANAGER', 'HR_MANAGER')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('leaves', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.leave')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile'),
        ),
    ]
